basePath: /
definitions:
  modelsstruct.Domain:
    properties:
      created_at:
        type: string
      flag:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
  modelsstruct.Domains:
    properties:
      domains:
        items:
          $ref: '#/definitions/modelsstruct.Domain'
        type: array
    type: object
  modelsstruct.Flag:
    properties:
      set_flag:
        type: integer
    required:
    - set_flag
    type: object
  modelsstruct.Price:
    properties:
      country:
        type: string
      country1:
        type: string
      country2:
        type: string
      geo:
        type: string
      id:
        type: integer
      money:
        type: string
      name:
        type: string
      new:
        type: string
      old:
        type: string
      tel:
        type: string
    type: object
  modelsstruct.Prices:
    properties:
      prices:
        items:
          $ref: '#/definitions/modelsstruct.Price'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Helper to add price.js
  title: GEO Support API
  version: "0.01"
paths:
  /api/domains/:
    post:
      consumes:
      - application/json
      description: Show all folders in dirrectory
      operationId: get-all-domains
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modelsstruct.Domains'
      summary: Get all domains
  /api/domains/{id}:
    post:
      consumes:
      - application/json
      description: 'set_flag is out parameters: 0 - new(set automatic), 1 - active,
        2 - ignore'
      operationId: set-flag-domain
      parameters:
      - description: id domain
        in: query
        name: id
        required: true
        type: integer
      - description: set flag
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modelsstruct.Flag'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Set flag to domain
  /api/prices/:
    get:
      consumes:
      - application/json
      description: Get all prices
      operationId: get-all-prices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modelsstruct.Prices'
      summary: Get all prices
  /api/prices/set_price:
    post:
      consumes:
      - application/json
      description: set price
      operationId: set-price
      parameters:
      - description: required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modelsstruct.Price'
      produces:
      - application/json
      responses:
        "200":
          description: 'set_price": "ok"}'
          schema:
            type: json
      summary: Set price
  /api/prices/update_price:
    post:
      consumes:
      - application/json
      description: Update price
      operationId: update-price
      parameters:
      - description: required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modelsstruct.Price'
      produces:
      - application/json
      responses:
        "200":
          description: 'update_price": "ok"}'
          schema:
            type: json
      summary: Update price
swagger: "2.0"
